### ISSUE TITLE
strand.md: s/notion/pseudo-code accessor/?

### ISSUE THREAD

**Issue by rns** [jeffreykegler/kollos#29]
rule notion -> `Rule` pseudo-code accessor
dotted rule notion -> `DR` pseudo-code accessor

seem to be a better fit for contexts like 

>A rule notion, when applied to a dotted rule, is equivalent to that rule notion applied to the rule of the dotted rule.

and

>A dotted rule notion, when applied to a Earley item, is equivalent to that dotted rule notion applied to the dotted rule of the Earley item.

**Comment by jeffreykegler** [comment]
That "notion" term I've adopted from a recent math paper.  It means that if it's an "idea", or "notion" which only makes sense for rules, but my language applies it to an Earley item, then it really applies to the Earley item.  So we have "start Earley items", which are Earley items which contain start rules.

It's a little difficult, but replaces a lot of tedious & repetitive definitions.  Many papers simply apply terms more or less at will, and leave it to the reader to puzzle it out.

**Comment by rns** [comment]
"notion" works as a term, but I can't help feeling that "pseudo-accessor" would work just as well in the context with the benefit being a lower number of terms.

**Comment by jeffreykegler** [comment]
"Notions" are notions in ordinary English.  The pseudo-code accessors are elements of the syntax of the pseudo-code, like `Accessor(x)`.  So these are two very different things.
