### ISSUE TITLE
strand.md: Case consistency for pseudo-code accessors

### ISSUE THREAD

**Issue by rns** [jeffreykegler/kollos#33]
e.g. (1) `Forward-inter-nucleotide` vs. (2) `Forward-Inter-Nucleotide` vs (3) `forward-inter-nucleotide` -- pick one

The current doc is mostly (1), so, unless (3) is preferred, consistency can be ensured by correcting Forward-Inter-Nucleotide, Reverse-Inter-Nucleotide, Forward-Intra-Nucleotide, and Reverse-Intra-Nucleotide.

**Comment by jeffreykegler** [comment]
Thanks!  Fixed in the above referenced commit.
