### ISSUE TITLE
strand.md: left/right vs. forward/reverse

### ISSUE THREAD

**Issue by rns** [jeffreykegler/kollos#34]
nucleobases are left/right, while the corresponding nucleotides are forward/reverse. 

Perhaps, use forward/reverse for nucleobases, so that, e.g. a forward nucleobase corresponds to forward (inter or intra) nucleotide rule to allow writing

>`Forward-inter-nucleotide([X ::= . A B C]) = [X-F ::= ]`
`Reverse-inter-nucleotide([X ::= . A B C]) = [X-R ::= A B C]`

**Comment by jeffreykegler** [comment]
I noticed this, but when it came to the nucleobases, I thought left/right was clearer.  When it came to nucleotides, we got into matters of the *left* nucleobase being on the far *right* of the *RHS*, and *left* nucleotides only occurring at the *right* edge of a bocage.

**Comment by rns** [comment]
I tried to play an Occam razor card here -- nucleobases lead to nucleotides so that could be more consistent if the same pair of adjectives is used to characterise both, and forward/reverse nucleotides (and hence, nucleobases) seem to make more sense. Left nucleobase producing forward nucleotide feels a bit unintuitive to me.

FWIW, there are 2 "reverse nucleobase" occurences later in the doc.

**Comment by jeffreykegler** [comment]
I'll look at the "reverse nucleobase" thing.

**Comment by jeffreykegler** [comment]
On this one, you're right.  I should change "left nucleobase" to "forward nucleobase" and "right nucleobase to reverse nucleobase".

**Comment by jeffreykegler** [comment]
Fixed in the above referenced commit.
