### ISSUE TITLE
strand.md: bocage -- terminal node length

### ISSUE THREAD

**Issue by rns** [jeffreykegler/kollos#42]
As in "The length of a terminal node is always one".

Doesn't that length it depend on the input model? Or is it always token-per-earleme fore strand parsing?

**Comment by jeffreykegler** [comment]
Variable length tokens will be eliminated in future Libmarpa versions.  Nobody ever used them and they add complexity which gets in the way of new features.  These new features seem likely to accomplish anything that variable length tokens might, in an easier-to-comprehend way.
