### ISSUE TITLE
strand.md: If node is a node ...

### ISSUE THREAD

**Issue by rns** [jeffreykegler/kollos#43]
As in 

> If `node` is a node, then `Links(node)` is the pseudo-code accessor that returns the set of links for node.

preceded by 

>Every non-terminal node has zero or more "source links", which describe why the node exists. If the node is a start rule prediction its source is not tracked, and it will have zero links. All other non-terminal nodes have one or more links.

Perhaps either 'If `node` is not a start rule prediction node' or just `Links(node)` is the pseudo-code accessor that returns the set of links for `node` if `Links` can return zero set?

**Comment by jeffreykegler** [comment]
Fixed in the above referenced commit.  Thanks!
